CountriesURL = {"Afghanistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_afghanistan/id2415875/",
"Albania":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_albania/id2428601/",
"Algerie":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_algerie/id2414745/",
"Andorra":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinformasjon-for-andorra/id2416242/",
"Angola":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_angola/id2415995/",
"Antigua & Barbuda":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_antigua_barbuda/id2428958/",
"Antigua Og Barbuda":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_antigua_barbuda/id2428958/",
"Argentina":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_argentina/id2415477/",
"Armenia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_armenia/id2416297/",
"Aserbajdsjan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_aserbajdsjan/id2428524/",
"Australia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_australia/id2415524/",
"Bahamas":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bahamas/id2428963/",
"Bahrain":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/bahrain_reiseinfo/id2428526/",
"Bangladesh":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bangladesh/id2415564/",
"Barbados":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/barbados---reiseinformasjon/id2428970/",
"Belgia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_belgia/id2414842/",
"Belize":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/belize---reiseinformasjon/id2428562/",
"Benin":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/benin---reiseinformasjon/id2424173/",
"Bhutan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bhutan/id2414742/",
"Bolivia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bolivia/id2415332/",
"Bosnia-Hercegovina":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bosnia/id2416500/",
"Botswana":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_botswana/id2416413/",
"Brasil":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_brasil/id2415169/",
"Brunei Darussalam":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_brunei/id2415974/",
"Bulgaria":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_bulgaria/id2416997/",
"Burkina Faso":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_burkinafaso/id2414675/",
"Burundi":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_burundi/id2415929/",
"Canada":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_canada/id2414944/",
"Chile":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_chile/id2414751/",
"Colombia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_colombia/id2414850/",
"Cookøyene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_cookoyene/id2415553/",
"Costa Rica":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_costarica/id2428563/",
"Cuba":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_cuba/id2415595/",
"Danmark":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_danmark/id2415976/",
"De forente arabiske emirater":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_emiratene/id2428549/",
"Den demokratiske republikken Kongo":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_drkongo/id2416057/",
"Den dominikanske republikk":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_dominikanske/id2415685/",
"Den sentralafrikanske republikk":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/sar_reiseinfo/id2429021/",
"Djibouti":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_djibouti/id2414710/",
"Dominica":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/dominica---reiseinformasjon/id2428976/",
"Ecuador":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_ecuador/id2414757/",
"Egypt":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_egypt/id2415880/",
"Ekvatorial-Guinea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_ekvatorialguinea/id2416217/",
"El Salvador":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_elsalvador/id2428564/",
"Elfenbenskysten":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_elfernbenskysten/id2414708/",
"Eritrea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_eritrea/id2429020/",
"Estland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_estland/id2417117/",
"Eswatini":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_ewatini/id2414925/",
"Etiopia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_etiopia/id2414712/",
"Fiji":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_fiji/id2415529/",
"Filippinene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_filippinene/id2416248/",
"Finland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_finland/id2424334/",
"Frankrike":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_frankrike/id2429004/",
"Gabon":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_gabon/id2416221/",
"Gambia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_gambia/id2414679/",
"Georgia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_georgia/id2428525/",
"Ghana":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinformasjon-for-ghana/id2414681/",
"Grenada":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_grenada/id2428980/",
"Guatemala":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_guatemala/id2428566/",
"Guinea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_guinea/id2414683/",
"Guinea-Bissau":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_guineabissau/id2414888/",
"Guyana":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_guyana/id2415199/",
"Haiti":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_haiti/id2415686/",
"Hellas":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_hellas/id2414955/",
"Honduras":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_honduras/id2428569/",
"Hviterussland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/hviterussland_reiseinformasjon/id2429135/",
"India":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_india/id2414743/",
"Indonesia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_indonesia/id2415692/",
"Irak":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_irak/id2428572/",
"Iran":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_iran/id2414831/",
"Irland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_irland/id2428570/",
"Island":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_island/id2414936/",
"Israel":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_israel/id2417120/",
"Italia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_italia/id2416484/",
"Jamaica":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_jamaica/id2428981/",
"Japan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_japan/id2415973/",
"Jemen":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_jemen/id2416418/",
"Jordan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_jordan/id2428573/",
"Kambodsja":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kambodsja/id2415096/",
"Kamerun":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kamerun/id2424175/",
"Kapp Verde":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kappverde/id2414891/",
"Kasakhstan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kasakhstan/id2428578/",
"Kenya":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kenya/id2414927/",
"Kina":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kina/id2414833/",
"Kirgisistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kirgisistan/id2428584/",
"Kiribati":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kiribati/id2429127/",
"Komorene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/komorene_reiseinfo/id2740675/",
"Kosovo":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kosovo/id2428615/",
"Kroatia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kroatia/id2417198/",
"Kuwait":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kuwait/id2428547/",
"Kypros":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_kypros/id2414993/",
"Laos":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_laos/id2424428/",
"Latvia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_latvia/id2414940/",
"Lesotho":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_lesotho/id2424507/",
"Libanon":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_libanon/id2415116/",
"Liberia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_liberia/id2414685/",
"Libya":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_libya/id2415885/",
"Liechtenstein":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_liechtenstein/id2415978/",
"Litauen":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_litauen/id2417192/",
"Luxembourg":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_luxembourg/id2415570/",
"Madagaskar":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_madagaskar/id2414947/",
"Malawi":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_malawi/id2415982/",
"Malaysia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_malaysia/id2415975/",
"Maldivene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_maldivene/id2428949/",
"Mali":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mali/id2424320/",
"Malta":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_malta/id2416492/",
"Marokko":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_marokko/id2424344/",
"Marshalløyene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_marshallislands/id2429128/",
"Mauritania":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mauritania/id2429137/",
"Mauritius":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinformasjon-for-mauritius/id2414916/",
"Mexico":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mexico/id2416296/",
"Mikronesiaføderasjonen":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mikronesia/id2428986/",
"Moldova":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_moldova/id2414862/",
"Monaco":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/monaco---reiseinformasjon/id2464469/",
"Mongolia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mongolia/id2414841/",
"Montenegro":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_montenegro/id2416376/",
"Mosambik":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_mosambik/id2414919/",
"Myanmar":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_myanmar/id2417496/",
"Namibia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_namibia/id2424510/",
"Nauru":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nauru/id2428988/",
"Nederland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nederland/id2414872/",
"Nepal":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nepal/id2416354/",
"New Zealand":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_newzealand/id2415533/",
"Nicaragua":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nicaragua/id2428567/",
"Niger":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_niger/id2424308/",
"Nigeria":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nigeria/id2414670/",
"Nord-Korea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nordkorea/id2429138/",
"Nord-Makedonia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_nordmakedonia/id2416995/",
"Oman":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_oman/id2424415/",
"Pakistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_pakistan/id2428616/",
"Palau":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_palau/id2428989/",
"Palestina":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/palestina_reiseinfo/id2429013/",
"Panama":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_panama/id2428568/",
"Papua Ny-Guinea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinformasjon-for-papua-ny-guinea/id2415535/",
"Paraguay":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_paraguay/id2415478/",
"Peru":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_peru/id2414760/",
"Polen":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_polen/id2429019/",
"Portugal":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_portugal/id2414892/",
"Qatar":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/qatar_reiseinformasjon/id2464219/",
"Republikken Kongo":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_repkongo/id2416225/",
"Romania":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_romania/id2414864/",
"Russland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_russland/id2416298/",
"Rwanda":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_rwanda/id2415941/",
"Sao Tome & Principe":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saotome/id2416237/",
"Sao Tome Og Principe":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saotome/id2416237/",
"Sør-Afrika":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sorafrika/id2424513/",
"Sør-Korea":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sorkorea/id2416503/",
"Sør-Sudan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sorsudan/id2429140/",
"Saint Kitts og Nevis":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saintkitts/id2428982/",
"Saint Lucia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saintlucia/id2428983/",
"Saint Vincent og Grenadinene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saintvincent/id2428984/",
"Salomonøyene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_salomonoyene/id2428990/",
"Samoa":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_samoa/id2428993/",
"San Marino":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sanmarino/id2429005/",
"Saudi-Arabia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_saudiarabia/id2416470/",
"Senegal":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_senegal/id2414687/",
"Serbia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_serbia/id2415119/",
"Seychellene":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_seychellene/id2414928/",
"Sierra Leone":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sierraleone/id2414706/",
"Singapore":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_singapore/id2416992/",
"Slovakia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_slovakia/id2424323/",
"Slovenia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_slovenia/id2415327/",
"Somalia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_somalia/id2429007/",
"Spania":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_spania/id2416245/",
"Sri Lanka":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_srilanka/id2424492/",
"Storbritannia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_uk/id2417495/",
"Sudan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sudan/id2429022/",
"Surinam":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_surinam/id2415324/",
"Sveits":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sveits/id2416999/",
"Sverige":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_sverige/id2416998/",
"Syria":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/syria_reiseinfo/id2429139/",
"Tadsjikistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tadsjikistan/id2428585/",
"Tanzania":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tanzania/id2415554/",
"Thailand":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_thailand/id2415097/",
"Togo":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_togo/id2424313/",
"Tonga":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tonga/id2415548/",
"Trinidad og Tobago":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_triogto/id2428985/",
"Tsjad":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tsjad/id2429023/",
"Tsjekkia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tsjekkia/id2416409/",
"Tunisia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tunisia/id2414832/",
"Turkmenistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_turkmenistan/id2428588/",
"Tuvalu":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tuvalu/id2415551/",
"Tyrkia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tyrkia/id2414945/",
"Tyskland":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_tyskland/id2415120/",
"Uganda":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_uganda/id2415945/",
"Ukraina":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_ukraina/id2429141/",
"Ungarn":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_ungarn/id2424333/",
"Uruguay":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_uruguay/id2415333/",
"USA":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_usa/id2417194/",
"Usbekistan":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_usbekistan/id2416307/",
"Vanuatu":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_vanuatu/id2428998/",
"Venezuela":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_venezuela/id2414861/",
"Vietnam":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_vietnam/id2415578/",
"Zambia":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_zambia/id2429142/",
"Zimbabwe":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_zimbabwe/id2415585/",
"Øst-Timor":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_osttimor/id2415704/",
"Østerrike":"/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_osterrike/id2414941/"}

CountriesList = ['Afghanistan',
'Albania',
'Algerie',
'Andorra',
'Angola',
'Antigua & Barbuda',
'Antigua Og Barbuda',
'Argentina',
'Armenia',
'Aserbajdsjan',
'Australia',
'Bahamas',
'Bahrain',
'Bangladesh',
'Barbados',
'Belgia',
'Belize',
'Benin',
'Bhutan',
'Bolivia',
'Bosnia-Hercegovina',
'Botswana',
'Brasil',
'Brunei Darussalam',
'Bulgaria',
'Burkina Faso',
'Burundi',
'Canada',
'Chile',
'Colombia',
'Cookøyene',
'Costa Rica',
'Cuba',
'Danmark',
'De forente arabiske emirater',
'Den demokratiske republikken Kongo',
'Den dominikanske republikk',
'Den sentralafrikanske republikk',
'Djibouti',
'Dominica',
'Ecuador',
'Egypt',
'Ekvatorial-Guinea',
'El Salvador',
'Elfenbenskysten',
'Eritrea',
'Estland',
'Eswatini',
'Etiopia',
'Fiji',
'Filippinene',
'Finland',
'Frankrike',
'Gabon',
'Gambia',
'Georgia',
'Ghana',
'Grenada',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Hellas',
'Honduras',
'Hviterussland',
'India',
'Indonesia',
'Irak',
'Iran',
'Irland',
'Island',
'Israel',
'Italia',
'Jamaica',
'Japan',
'Jemen',
'Jordan',
'Kambodsja',
'Kamerun',
'Kapp Verde',
'Kasakhstan',
'Kenya',
'Kina',
'Kirgisistan',
'Kiribati',
'Komorene',
'Kosovo',
'Kroatia',
'Kuwait',
'Kypros',
'Laos',
'Latvia',
'Lesotho',
'Libanon',
'Liberia',
'Libya',
'Liechtenstein',
'Litauen',
'Luxembourg',
'Madagaskar',
'Malawi',
'Malaysia',
'Maldivene',
'Mali',
'Malta',
'Marokko',
'Marshalløyene',
'Mauritania',
'Mauritius',
'Mexico',
'Mikronesiaføderasjonen',
'Moldova',
'Monaco',
'Mongolia',
'Montenegro',
'Mosambik',
'Myanmar',
'Namibia',
'Nauru',
'Nederland',
'Nepal',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'Nord-Korea',
'Nord-Makedonia',
'Oman',
'Pakistan',
'Palau',
'Palestina',
'Panama',
'Papua Ny-Guinea',
'Paraguay',
'Peru',
'Polen',
'Portugal',
'Qatar',
'Republikken Kongo',
'Romania',
'Russland',
'Rwanda',
'Sao Tome & Principe',
'Sao Tome Og Principe',
'Sør-Afrika',
'Sør-Korea',
'Sør-Sudan',
'Saint Kitts og Nevis',
'Saint Lucia',
'Saint Vincent Og Grenadinene',
'Salomonøyene',
'Samoa',
'San Marino',
'Saudi-Arabia',
'Senegal',
'Serbia',
'Seychellene',
'Sierra Leone',
'Singapore',
'Slovakia',
'Slovenia',
'Somalia',
'Spania',
'Sri Lanka',
'Storbritannia',
'Sudan',
'Surinam',
'Sveits',
'Sverige',
'Syria',
'Tadsjikistan',
'Tanzania',
'Thailand',
'Togo',
'Tonga',
'Trinidad og Tobago',
'Tsjad',
'Tsjekkia',
'Tunisia',
'Turkmenistan',
'Tuvalu',
'Tyrkia',
'Tyskland',
'Uganda',
'Ukraina',
'Ungarn',
'Uruguay',
'USA',
'Usbekistan',
'Vanuatu',
'Venezuela',
'Vietnam',
'Zambia',
'Zimbabwe',
'Øst-Timor',
'Østerrike']

CountriesEng = {"Afghanistan":"Afghanistan",
"Albania":"Albania",
"Algerie":"Algeria",
"Andorra":"Andorra",
"Angola":"Angola",
"Antigua & Barbuda":"Antigua-and-Barbuda",
"Antigua Og Barbuda":"Antigua-and-Barbuda",
"Argentina":"Argentina",
"Armenia":"Armenia",
"Aserbajdsjan":"Azerbaijan",
"Australia":"Australia",
"Bahamas":"Bahamas",
"Bahrain":"Bahrain",
"Bangladesh":"Bangladesh",
"Barbados":"Barbados",
"Belgia":"Belgium",
"Belize":"Belize",
"Benin":"Benin",
"Bhutan":"Bhutan",
"Bolivia":"Bolivia",
"Bosnia-Hercegovina":"Bosnia-and-Herzegovina",
"Botswana":"Botswana",
"Brasil":"Brazil",
"Brunei Darussalam":"Brunei",
"Bulgaria":"Bulgaria",
"Burkina Faso":"Burkina-Faso",
"Burundi":"Burundi",
"Canada":"Canada",
"Chile":"Chile",
"Colombia":"Colombia",
"Cookøyene":"not found",
"Costa Rica":"Costa-Rica",
"Cuba":"Cuba",
"Danmark":"Denmark",
"De forente arabiske emirater":"United-Arab-Emirates",
"Den demokratiske republikken Kongo":"Congo",
"Den dominikanske republikk":"Dominican-Republic",
"Den sentralafrikanske republikk":"not found",
"Djibouti":"Djibouti",
"Dominica":"Dominica",
"Ecuador":"Ecuador",
"Egypt":"Egypt",
"Ekvatorial-Guinea":"Equatorial-Guinea",
"El Salvador":"El-Salvador",
"Elfenbenskysten":"cote-d-ivoire",
"Eritrea":"Eritrea",
"Estland":"Estonia",
"Eswatini":"Swaziland",
"Etiopia":"Ethiopia",
"Fiji":"Fiji",
"Filippinene":"Philippines",
"Finland":"Finland",
"Frankrike":"France",
"Gabon":"Gabon",
"Gambia":"Gambia",
"Georgia":"Georgia",
"Ghana":"Ghana",
"Grenada":"Grenada",
"Guatemala":"Guatemala",
"Guinea":"Guinea",
"Guinea-Bissau":"Guinea-Bissau",
"Guyana":"Guyana",
"Haiti":"Haiti",
"Hellas":"Greece",
"Honduras":"Honduras",
"Hviterussland":"Belarus",
"India":"India",
"Indonesia":"Indonesia",
"Irak":"Iraq",
"Iran":"Iran",
"Irland":"Ireland",
"Island":"Iceland",
"Israel":"Israel",
"Italia":"Italy",
"Jamaica":"Jamaica",
"Japan":"Japan",
"Jemen":"Yemen",
"Jordan":"Jordan",
"Kambodsja":"Cambodia",
"Kamerun":"Cameroon",
"Kapp Verde":"Cabo-Verde",
"Kasakhstan":"Kazakhstan",
"Kenya":"Kenya",
"Kina":"China",
"Kirgisistan":"Kyrgyzstan",
"Kiribati":"not found",
"Komorene":"Comoros",
"Kosovo":"not found",
"Kroatia":"Croatia",
"Kuwait":"Kuwait",
"Kypros":"Cyprus",
"Laos":"Laos",
"Latvia":"Latvia",
"Lesotho":"Lesotho",
"Libanon":"Lebanon",
"Liberia":"Liberia",
"Libya":"Libya",
"Liechtenstein":"Liechtenstein",
"Litauen":"Lithuania",
"Luxembourg":"Luxembourg",
"Madagaskar":"Madagascar",
"Malawi":"Malawi",
"Malaysia":"Malaysia",
"Maldivene":"Maldives",
"Mali":"Mali",
"Malta":"Malta",
"Marokko":"Morocco",
"Marshalløyene":"Marshall-Islands",
"Mauritania":"Mauritania",
"Mauritius":"Mauritius",
"Mexico":"Mexico",
"Mikronesiaføderasjonen":"not found",
"Moldova":"Moldova",
"Monaco":"Monaco",
"Mongolia":"Mongolia",
"Montenegro":"Montenegro",
"Mosambik":"Mozambique",
"Myanmar":"Myanmar",
"Namibia":"Nambia",
"Nauru":"not found",
"Nederland":"Netherlands",
"Nepal":"Nepal",
"New Zealand":"New-Zealand",
"Nicaragua":"Nicaragua",
"Niger":"Niger",
"Nigeria":"Nigeria",
"Nord-Korea":"not found",
"Nord-Makedonia":"Macedonia",
"Oman":"Oman",
"Pakistan":"Pakistan",
"Palau":"not found",
"Palestina":"State-of-Palestine",
"Panama":"Panama",
"Papua Ny-Guinea":"Papua-New-Guinea",
"Paraguay":"Paraguay",
"Peru":"Peru",
"Polen":"Poland",
"Portugal":"Portugal",
"Qatar":"Qatar",
"Republikken Kongo":"not found",
"Romania":"Romania",
"Russland":"Russia",
"Rwanda":"Rwanda",
"Sao Tome & Principe":"Sao-Tome-and-Principe",
"Sao Tome Og Principe":"Sao-Tome-and-Principe",
"Sør-Afrika":"South-Africa",
"Sør-Korea":"South-Korea",
"Sør-Sudan":"South-Sudan",
"Saint Kitts og Nevis":"saint-kitts-and-nevis",
"Saint Lucia":"saint-lucia",
"Saint Vincent og Grenadinene":"saint-vincent-and-the-grenadines",
"Salomonøyene":"solomon-islands",
"Samoa":"samoa",
"San Marino":"san-marino",
"Saudi-Arabia":"saudi-arabia",
"Senegal":"senegal",
"Serbia":"serbia",
"Seychellene":"seychelles",
"Sierra Leone":"sierra-leone",
"Singapore":"singapore",
"Slovakia":"slovakia",
"Slovenia":"slovenia",
"Somalia":"somalia",
"Spania":"spain",
"Sri Lanka":"sri-lanka",
"Storbritannia":"uk",
"Sudan":"sudan",
"Surinam":"suriname",
"Sveits":"switzerland",
"Sverige":"sweden",
"Syria":"syria",
"Tadsjikistan":"tajikistan",
"Tanzania":"tanzania",
"Thailand":"thailand",
"Togo":"togo",
"Tonga":"not found",
"Trinidad og Tobago":"trinidad-and-tobago",
"Tsjad":"chad",
"Tsjekkia":"czech-republic",
"Tunisia":"tunisia",
"Turkmenistan":"not found",
"Tuvalu":"not found",
"Tyrkia":"turkey",
"Tyskland":"germany",
"Uganda":"uganda",
"Ukraina":"ukraine",
"Ungarn":"hungary",
"Uruguay":"uruguay",
"USA":"usa",
"Usbekistan":"uzbekistan",
"Vanuatu":"vanuata",
"Venezuela":"venezuela",
"Vietnam":"vietnam",
"Zambia":"zambia",
"Zimbabwe":"zimbabwe",
"Øst-Timor":"timor-leste",
"Østerrike":"austria",}